module.exports = {
  global: {
    zh: {
      navTitle: '百色景点美食指南',
      networkError: '网络异常，请稍后重试',
      loading: '加载中...',
      noData: '暂无数据',
      confirm: '确定',
      cancel: '取消',
      success: '操作成功',
      fail: '操作失败'
    },
    en: {
      navTitle: 'Baise Guide',
      networkError: 'Network error, please try again',
      loading: 'Loading...',
      noData: 'No data',
      confirm: 'OK',
      cancel: 'Cancel',
      success: 'Success',
      fail: 'Failed'
    }
  },
  index: {
    zh: {
      searchPlaceholder: '搜索景点/美食/商户',
      hotAttractions: '热门景点',
      hotFoods: '热门美食',
      news: '文旅资讯',
      recommend: '猜你喜欢',
      more: '更多',
      refresh: '换一批',
      reachBottom: '已经逛到底啦～',
      loadFail: '加载失败',
      switchZhSuccess: '已切换为中文',
      switchEnSuccess: 'Switched to English'
    },
    en: {
      searchPlaceholder: 'Search scenic spots/food',
      hotAttractions: 'Hot Attractions',
      hotFoods: 'Hot Food',
      news: 'Cultural News',
      recommend: 'For You',
      more: 'More',
      refresh: 'Refresh',
      reachBottom: "You've reached the end～",
      loadFail: 'Load failed',
      switchZhSuccess: '已切换为中文',
      switchEnSuccess: 'Switched to English'
    }
  },
  login: {
    zh: {
      title: '登录',
      registerTitle: '注册',
      wechatLogin: '微信一键登录',
      accountLogin: '账号登录',
      phone: '手机号',
      phoneRequired: '请输入手机号',
      phoneFormat: '手机号格式不正确',
      password: '密码',
      passwordRequired: '请输入密码',
      passwordRule: '密码需8-16位，包含大小写字母和数字',
      confirmPassword: '确认密码',
      confirmPwdSame: '两次密码输入不一致',
      pwdStrengthWeak: '弱',
      pwdStrengthMiddle: '中',
      pwdStrengthStrong: '强',
      protocolRequired: '请阅读并同意用户协议和隐私政策',
      authDesc: '用于完善用户资料',
      loginSuccess: '登录成功',
      loginFail: '登录失败',
      registerSuccess: '注册成功',
      registerFail: '注册失败',
      noAccount: '没有账号？去注册',
      hasAccount: '已有账号？去登录'
    },
    en: {
      title: 'Login',
      registerTitle: 'Register',
      wechatLogin: 'Login with WeChat',
      accountLogin: 'Account Login',
      phone: 'Phone',
      phoneRequired: 'Please enter phone number',
      phoneFormat: 'Invalid phone number',
      password: 'Password',
      passwordRequired: 'Please enter password',
      passwordRule: '8-16 chars with uppercase, lowercase and numbers',
      confirmPassword: 'Confirm Password',
      confirmPwdSame: 'Passwords do not match',
      pwdStrengthWeak: 'Weak',
      pwdStrengthMiddle: 'Medium',
      pwdStrengthStrong: 'Strong',
      protocolRequired: 'Please agree to the terms',
      authDesc: 'For user profile',
      loginSuccess: 'Login successful',
      loginFail: 'Login failed',
      registerSuccess: 'Registration successful',
      registerFail: 'Registration failed',
      noAccount: 'No account? Register',
      hasAccount: 'Have account? Login'
    }
  },
  attractionList: {
    zh: {
      title: '景点列表',
      categoryAll: '全部',
      categoryRed: '红色景点',
      categoryNature: '自然风光',
      categoryEthnic: '民族村寨',
      regionAll: '全部区域',
      searchPlaceholder: '搜索景点',
      filter: '筛选',
      sortHot: '热度',
      sortRating: '评分',
      sortDistance: '距离',
      noData: '暂无景点',
      meter: '米',
      km: '公里'
    },
    en: {
      title: 'Attractions',
      categoryAll: 'All',
      categoryRed: 'Red Tourism',
      categoryNature: 'Nature',
      categoryEthnic: 'Ethnic Villages',
      regionAll: 'All Regions',
      searchPlaceholder: 'Search attractions',
      filter: 'Filter',
      sortHot: 'Hot',
      sortRating: 'Rating',
      sortDistance: 'Distance',
      noData: 'No attractions',
      meter: 'm',
      km: 'km'
    }
  },
  attractionDetail: {
    zh: {
      title: '景点详情',
      favorite: '收藏',
      favorited: '已收藏',
      share: '分享',
      address: '地址',
      openTime: '开放时间',
      ticket: '门票',
      phone: '联系电话',
      copySuccess: '复制成功',
      introduction: '景点介绍',
      tips: '游玩贴士',
      myRating: '我的评分',
      reviews: '用户评论',
      writeReview: '写评论',
      nearbyFood: '附近美食',
      punchIn: '打卡',
      punchedIn: '已打卡',
      like: '点赞',
      navigate: '导航'
    },
    en: {
      title: 'Attraction Detail',
      favorite: 'Favorite',
      favorited: 'Favorited',
      share: 'Share',
      address: 'Address',
      openTime: 'Opening Hours',
      ticket: 'Ticket',
      phone: 'Phone',
      copySuccess: 'Copied',
      introduction: 'Introduction',
      tips: 'Tips',
      myRating: 'My Rating',
      reviews: 'Reviews',
      writeReview: 'Write Review',
      nearbyFood: 'Nearby Food',
      punchIn: 'Check In',
      punchedIn: 'Checked In',
      like: 'Like',
      navigate: 'Navigate'
    }
  },
  foodList: {
    zh: {
      title: '美食列表',
      categoryAll: '全部',
      categorySnack: '特色小吃',
      categoryRestaurant: '餐厅',
      categoryLocal: '地方特产',
      categoryDessert: '甜品茶饮',
      regionAll: '全部区域',
      noData: '暂无美食'
    },
    en: {
      title: 'Food',
      categoryAll: 'All',
      categorySnack: 'Snacks',
      categoryRestaurant: 'Restaurants',
      categoryLocal: 'Local Specialties',
      categoryDessert: 'Dessert & Drinks',
      regionAll: 'All Regions',
      noData: 'No food'
    }
  },
  search: {
    zh: {
      title: '搜索',
      placeholder: '搜索景点/美食/商户',
      history: '搜索历史',
      hotSearch: '热门搜索',
      clear: '清空',
      all: '全部',
      attractions: '景点',
      food: '美食',
      noResult: '暂无搜索结果',
      emptySearchKey: '请输入搜索内容'
    },
    en: {
      title: 'Search',
      placeholder: 'Search...',
      history: 'History',
      hotSearch: 'Hot Searches',
      clear: 'Clear',
      all: 'All',
      attractions: 'Attractions',
      food: 'Food',
      noResult: 'No results found',
      emptySearchKey: 'Please enter search content'
    }
  },
  feedback: {
    zh: {
      title: '意见反馈',
      typeSuggest: '功能建议',
      typeBug: 'Bug反馈',
      typeComplaint: '投诉建议',
      typeOther: '其他',
      content: '反馈内容',
      contentRequired: '请输入反馈内容',
      images: '上传图片',
      maxImages: '最多上传3张图片',
      contact: '联系方式',
      submit: '提交反馈',
      submitSuccess: '提交成功',
      submitFailed: '提交失败'
    },
    en: {
      title: 'Feedback',
      typeSuggest: 'Suggestion',
      typeBug: 'Bug Report',
      typeComplaint: 'Complaint',
      typeOther: 'Other',
      content: 'Content',
      contentRequired: 'Please enter content',
      images: 'Images',
      maxImages: 'Max 3 images',
      contact: 'Contact',
      submit: 'Submit',
      submitSuccess: 'Submitted successfully',
      submitFailed: 'Submit failed'
    }
  },
  comment: {
    zh: {
      title: '写评论',
      rating: '评分',
      ratingRequired: '请进行评分',
      tags: '标签',
      content: '评论内容',
      contentRequired: '请输入评论内容',
      maxImages: '最多上传3张图片',
      submit: '提交评论',
      submitSuccess: '评论成功',
      submitFailed: '评论失败',
      tagWorth: '值得一去',
      tagBeautiful: '风景优美',
      tagGuide: '讲解专业',
      tagDelicious: '味道正宗',
      tagAffordable: '性价比高',
      tagClean: '环境整洁'
    },
    en: {
      title: 'Write Review',
      rating: 'Rating',
      ratingRequired: 'Please rate',
      tags: 'Tags',
      content: 'Content',
      contentRequired: 'Please enter content',
      maxImages: 'Max 3 images',
      submit: 'Submit',
      submitSuccess: 'Review submitted',
      submitFailed: 'Submit failed',
      tagWorth: 'Worth visiting',
      tagBeautiful: 'Beautiful scenery',
      tagGuide: 'Professional guide',
      tagDelicious: 'Delicious',
      tagAffordable: 'Good value',
      tagClean: 'Clean environment'
    }
  }
}
